apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-redis
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-redis
        image: redis:alpine
