apiVersion: v1
kind: Service

metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  namespace: singouins
  name: sep-backend-redis-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: redis
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 6379
    name: redis
  - protocol: TCP
    port: 9121
    name: metrics
