apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-metrics
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8008"
      labels:
        app: metrics
        tier: sep-backend
    spec:
      restartPolicy: Always

      initContainers:
      - name: sep-backend-metrics-init
        image: busybox
        volumeMounts:
        - name: code
          mountPath: /code
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget   https://github.com/lordslair/sep-backend/archive/master.zip -O /tmp/sep.zip &&
              wget -q https://api.github.com/repos/lordslair/sep-backend/commits/master -O - 2&>1 | grep '^  .sha' | cut -d'\"' -f4 > /code/.git &&
              unzip  /tmp/sep.zip -d /tmp/ &&
              cp -a  /tmp/sep-backend-master/metrics/* /code/ &&
              rm -rf /tmp/sep-backend-master &&
              rm -rf /tmp/sep.zip
          ) || echo 1"
        ]

      containers:
      - name: sep-backend-metrics
        image: alpine
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
        ports:
        - containerPort: 8008
