apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-metrics-secret
type: Opaque
stringData:
  sql-user: '<SECRET>'
  sql-pass: '<SECRET>'
  sql-host: '<SECRET>'
  sql-db:   '<SECRET>'
