apiVersion: v1
kind: ConfigMap
metadata:
  name: sep-backend-nginx
  labels:
    tier: sep-backend
data:
  config : |
    server {
      listen      80;
      server_name <URL>;

      location /.well-known/acme-challenge/ {
          root /var/www/certbot;
      }

      location / {
        auth_basic "Basic Auth";
        auth_basic_user_file /etc/nginx/htpasswd/htpasswd;
        proxy_pass http://sep-backend-wiki:5000;
        proxy_http_version      1.1;
      }
    }

    server {
      listen 443 ssl;
      server_name <URL>;

      add_header          Strict-Transport-Security 'max-age=63072000; includeSubDomains; preload;' always;

      ssl_session_cache   shared:SSL:10m;
      ssl_session_timeout 1440m;
      ssl_session_tickets off;

      ssl_protocols       TLSv1.2 TLSv1.3;
      ssl_prefer_server_ciphers on;
      ssl_ciphers         ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;

      ssl_certificate     /etc/letsencrypt/live/<URL>/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/<URL>/privkey.pem;

      location / {
        auth_basic "Basic Auth";
        auth_basic_user_file /etc/nginx/htpasswd/htpasswd;
        proxy_pass http://sep-backend-wiki:5000;
        proxy_http_version      1.1;
      }
    }

    server {
      listen      80;
      server_name <URL>;

        location / {
                proxy_set_header    Host $host;
                proxy_set_header    X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto $scheme;
                proxy_pass          http://sep-backend-phpmyadmin-svc/;
                proxy_read_timeout  90;
        }
    }

    server {
      listen        80 default_server;
      access_log    off;
      error_log     off;
      log_not_found off;
      deny          all;
    }
