apiVersion: v1
kind: Service
metadata:
  name: sep-backend-nginx
  labels:
    tier: sep-backend
spec:
  selector:
    app: nginx
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 80
    name: http
  - protocol: TCP
    port: 443
    name: https
