apiVersion: v1
kind: Secret
metadata:
  name: sep-backend-api-secret
type: Opaque
stringData:
  jwt-secret: '<SECRET>'
  smtp-from: '<SECRET>'
  smtp-server: '<SECRET>'
  smtp-user: '<SECRET>'
  smtp-pass: '<SECRET>'
  smtp-host: '<SECRET>'
