apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-api-secret
type: Opaque
stringData:
  jwt-secret: '<SECRET>'
  smtp-from: '<SECRET>'
  smtp-server: '<SECRET>'
  smtp-user: '<SECRET>'
  smtp-pass: '<SECRET>'
  smtp-host: '<SECRET>'
  sql-user: '<SECRET>'
  sql-pass: '<SECRET>'
  redis-host: '<SECRET>'
