apiVersion: v1
kind: ConfigMap

metadata:
  namespace: singouins
  name: sep-backend-mariadb
  labels:
    tier: sep-backend
data:
  config : |
    [mysqld]
    #
    # * Custom Settings
    #
    # To avoid :
    # [ERROR] Invalid (old?) table or database name 'lost+found'
    ignore-db-dir = lost+found
