apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-mariadb
  labels:
    tier: sep-backend
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
        prometheus.io/path: "/metrics"
      labels:
        app: mariadb
        tier: sep-backend
    spec:

      containers:
        - image: mariadb:10.4
          name: sep-backend-mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sep-backend-mariadb-secret
                  key: pass
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/mariadb.conf.d
        - name: mariadb-exporter
          image: prom/mysqld-exporter
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: sep-backend-mariadb-secret
                  key: exporter-dsn
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
          ports:
          - containerPort: 9104
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: sep-backend-mariadb-db
        - name: config
          configMap:
            name: sep-backend-mariadb
            items:
              - key: config
                path: custom.cnf
