apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-mariadb-secret
type: Opaque
stringData:
  user: 'root'
  pass: '<PASSWORD>'
  exporter-dsn: 'mysqld-exporter:<PASSWORD>@(localhost:3306)/'
