apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sep-backend-mariadb-db
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
