apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-filestash-secret
type: Opaque
stringData:
  domain: filestash.domain.tld
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-backup-secret
type: Opaque
stringData:
  dblist: "XX,YY"
  dbhost: k8s-mariadb-service
  pcauser: <pcauser>
  pcapass: <pcapass>
