apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-discord
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-discord
        image: lordslair/singouins:discord-alpine3.7
        resources:
          limits:
            memory: 128Mi
            cpu: 50m
          requests:
            memory: 64Mi
            cpu: 10m
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: sql-pass
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: sql-user
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: sql-host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: sql-db
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: sep-backend-discord-secret
              key: token
