openapi: 3.0.0
info:
  description: ''
  version: 0.0.1
  title: S&P Internal API
  contact: {}
paths:

  /auth/login:
    post:
      tags:
        - '/auth: Authentificaton Requests'
      summary: Returns access_token & refresh_token
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthLoginPostBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthLoginResponse'
        '400':
          description: KO - Missing information in request
        '401':
          description: KO - Bad information in request

  /auth/refresh:
    post:
      tags:
        - '/auth: Authentificaton Requests'
      summary: Returns new access_token from refresh_token
      security:
        - refresh_token: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthRefreshResponse'

  /auth/infos:
    get:
      tags:
        - '/auth: Authentificaton Requests'
      summary: Get informations from an authenticated user
      security:
        - access_token: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthInfosResponse'
        '401':
          description: KO - Expired/Missing token
        '422':
          description: KO - Wrong token

components:
  schemas:
    AuthLoginPostBody:
      type: object
      properties:
        username:
          type: string
          format: string
        password:
          type: string
          format: string
    AuthLoginResponse:
      type: object
      properties:
        access_token:
          type: string
          format: string
        refresh_token:
          type: string
          format: string
    AuthRefreshResponse:
      type: object
      properties:
        access_token:
          type: string
          format: string
    AuthInfosResponse:
      type: object
      properties:
        logged_in_as:
          type: string
          format: string
  securitySchemes:
    refresh_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
    access_token:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - refresh_token: []
  - access_token: []
