apiVersion: v1
kind: Service
metadata:
  name: sep-backend-phpmyadmin-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: phpmyadmin
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 80
