apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-redis-commander
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
      tier: sep-backend
  template:
    metadata:
      labels:
        app: redis-commander
        tier: sep-backend
    spec:

      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        env:
        - name: REDIS_HOSTS
          value: instance1:sep-backend-redis-svc:6379
        - name: K8S_SIGTERM
          value: '1'
        ports:
        - name: redis-commander
          containerPort: 8081
