apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-backup
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backup
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-backup
        image: lordslair/easydbbackup:1.1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 32Mi
            cpu: 50m
          requests:
            memory: 16Mi
            cpu: 10m
        env:
          - name: DB_LIST
            valueFrom:
              secretKeyRef:
                name: sep-backend-backup-secret
                key: dblist
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: sep-backend-backup-secret
                key: dbhost
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: sep-backend-mariadb-secret
                key: port
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: sep-backend-mariadb-secret
                key: pass
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: sep-backend-mariadb-secret
                key: user
          - name: PCA_USER
            valueFrom:
              secretKeyRef:
                name: sep-backend-backup-secret
                key: pcauser
          - name: PCA_PASS
            valueFrom:
              secretKeyRef:
                name: sep-backend-backup-secret
                key: pcapass
          - name: PCA_HOST
            valueFrom:
              secretKeyRef:
                name: sep-backend-backup-secret
                key: pcahost
          - name: PCA_DIR
            valueFrom:
              secretKeyRef:
                name: sep-backend-backup-secret
                key: pcadir
